model_list:
  - model_name: nvidia/meta/llama-3.1-70b-instruct  # Custom alias
    litellm_params:
      model: "nvidia_nim/meta/llama-3.1-70b-instruct"  # e.g., "meta/llama-3.1-70b-instruct"
      api_key: "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"
      api_base: "https://integrate.api.nvidia.com/v1"
      max_tokens: 6000  # Mandatory for NVIDIA API :cite[10]
